### ISSUE TITLE
Support for 24 hour time

### ISSUE THREAD

**Issue by hagabla** [laconalabs/elliptical-datetime#5]
Referring to https://github.com/laconalabs/LaconaApp/issues/73

As requested

**Comment by brandonhorst** [comment]
Thanks.

This should probably be dependent on the locale. If it was 17:00/5pm, and I (as an American) typed "remind me to wash the dishes at 8:00", I would expect elliptical to understand that as 8pm, not 8:00/8am.

I imagine that non-American locales should still have the ability to enter am/pm, but it will not be suggested, and 8:00 without the am/pm should always mean 8:00/8am, regardless of the current time.

This will first require us to implement [elliptical-translate](https://github.com/brandonhorst/elliptical-translate), which is thankfully a fairly simple task. Actually working out the details of the 24-hour time will be harder.

**Comment by brandonhorst** [comment]
Implemented with c1456ed0f1ff63282dd8ef9f9d73c100c9bac2ec. Finally :)
